---
autoCollapseToc: true
categories:
- Getting Started
comment: true
date: "2020-01-20"
description: Information to get started in the course.
draft: false
featured_image: ""
featured_image_preview: ""
lastmod: "2019-08-25T16:22:42+08:00"
license: ""
math: true
show_description: false
show_in_homepage: true
tags:
- Getting Started
- Course Logistics
title: Getting Started in the class
toc: true
---

Welcome to Multiple Regression!  I'm looking forward to working with you this semester, getting to know each of you and hopefully helping to expand your skills as emerging data scientists. 

# What are we doing in this course?
I hope that by the end of the semester you will have a clear, confident identity as a regression modeller. Being able to work with data, fitting regression models, and being able to communicate what you did and what you found will be extremely valuable skills in quantitative-oriented work in your future. An article in [Harvard Business Review last year](https://hbr.org/2019/01/data-science-and-the-art-of-persuasion) identified six core skills for data scientists: project managment, data wrangling, data analysis, subject expertise, design, and storytelling. This course - while obviously heaviest in emphasis on analysis - will cultivate each of these skills to some degree, especially through the course project.

#Initial Course Administration Tasks

There are a few small, administrative things to get started. These should have done before the second week of class, but if you want a jump start on them, have at it!

1. Read the syllabus
1. Get a copy of [the textbook](https://www.amazon.com/STAT2-Modeling-Regression-Ann-Cannon-ebook-dp-B07K6Y99J3/dp/B07K6Y99J3/ref=mt_kindle?_encoding=UTF8&me=&qid=1579815019) (& see notes in the syllabus about the book)
1. Download the [PollEverywhere app](https://www.polleverywhere.com/mobile) to your phone or a device that you'll have with you in the classroom
1. Set up an account with [RStudio Cloud](https://rstudio.cloud/) (easiest via Google with your Smith account)
1. Join the [course Slack](https://join.slack.com/t/sds291-spring2020/shared_invite/enQtODc2NzU0MTU5MjAxLTFmZmU2OTc5OTIzMDU5MzU5ZTEzNjZkMDllYmRlYmQ4NzI2ZTM4Y2Y2N2M2MWRjY2ZjMDVlMGRjN2JmZjdiZWY). If you're new to Slack, look through the 
1. Add a 1-2 songs to [a playlist for our class](https://open.spotify.com/playlist/70l14LCdw5XOAyk1RHeuAO?si=Enp-jrtiSeKWhU4XYueiqg). I like playing music at the beginning of class and during in-class work time (there will be a lot), so add something you'd like to hear. See more [here](https://support.spotify.com/us/article/create-playlists-with-your-friends/) about adding to a collaborative playlist. If you don't have a Spotify account or have trouble adding songs, just put the song title and artist in the \#songs channel on the course slack. And remember what you added so you can tell me which songs are yours!

#Getting started with `R` & Refreshing Statistics

New to `R`? Feeling rusty on your introductory statistics material?*

1. Don't fret -- we'll do this all together, no need to feel like you have to do any prep before class.
1. If you _want_ to practice `R`, especially during the first few weeks of semester when the workload is a little lighter, try the [primers in RStudio Cloud](https://rstudio.cloud/learn/primers), especially the first four (don't worry about iterate or write functions)
1. Take a look back at your intro stats text book, or [this open source textbook](https://drive.google.com/file/d/0B-DHaDEbiOGkRHNndUlBaHVmaGM/edit). You might want to review normal distributions, tests of differences in means (t-tests), ANOVA, and interpretation of p-values and confidence intervals. We'll cover the regression specific material, but those ideas underlie much of regression. Again, I wouldn't stress about this at this point, but a very quick skim could help get the dust off your recall of this material.

*Many former students have had some anxiety coming into the class about the learning curve to learn `R`. I am fully anticipating -- and can empathize with! -- this nervousness. We will talk plenty about how to get going with `R` for those in the class who haven't used it before, with additional resources as we get going. We'll cover what you need in class, but if you want to do some extra practice in the first few weeks of the semester while things are (generally) quiet, it might be useful to do so.

